### ISSUE TITLE
SilverStripe 3.2

### ISSUE THREAD

**Issue by JorisDebonnet** [cwsoft/silverstripe-foldergallery#6]
As far as I can tell, this is perfectly compatible with SilverStripe 3.2. In fact, any 3.\* should be supported due to the newly adopted semantic versioning.

Perhaps a new version with a change in `composer.json` is in order? :)

**Comment by Juanitou** [comment]
Bump.

**Comment by cwsoft** [comment]
Won´t fix as I have no use case for this module anymore. However, feel free to fork and fix it for your needs. Cheers cwsoft
